movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movie_project/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    movie_name=models.CharField(max_length=250)
    movie_desc=models.TextField()
    Movie_year=models.IntegerField()
    movie_img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.movie_name

movie_project/movieapp/forms.py
from django import forms
from .models import movie

class movieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['movie_name', 'Movie_year', 'movie_desc', 'movie_img']

movie_project/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import movieForm
from .models import movie

# Create your views here.
def index(request):
    movies=movie.objects.all()
    context={
        'movie_list' :movies
    }
    return  render(request, 'index.html', context)
def movie_detail(request,movie_id):
    item=movie.objects.get(id=movie_id)
    return render(request,'details.html',{'movie': item})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('movie_name',)
        year = request.POST.get('movie_year', )
        desc = request.POST.get('movie_desc', )
        img = request.FILES['movie_img']
        from .models import movie
        movie=movie(movie_name=name, Movie_year=year, movie_desc=desc,movie_img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movies=movie.objects.get(id=id)
    form=movieForm(request.POST or None, request.FILES, instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form': form, 'movie': movies})

def delete(request,id):
    if request.method=='POST':
        movies=movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    <input type="text" name="movie_name" placeholder="Enter the movie name"><br>
    <input type="text" name="movie_year" placeholder="Enter the movie year"><br>
    <input type="text" name="movie_desc" placeholder="Enter the movie desc"><br>
    <input type="file" name="movie_img"><br>
    <input type="submit">
</form>
{% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style3.css'%}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-white bg-dark">
  <a class="navbar-brand" href="">Movies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie_project/templates/delete.html
<form method="POST" >
    {% csrf_token %}
    Do you want to delete the movie?
    <input type="submit">
</form>

movie_project/templates/details.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <img src="{{movie.movie_img.url}}" width="250" height="350"> <br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a><br>
        </div>
        <div class="col-sm-6">
            <h4>{{movie.movie_name}}</h4>
            <h5>{{movie.Movie_year}}</h5><br>
            {{movie.movie_desc}}</h6>
        </div>
    </div>
</div>




{% endblock %}

movie_project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<br>

<div class="container">
    <div class="col-md-12 text-right">
    <a class="btn btn-success" href="{% url 'movieapp:add_movie' %}">Add movie</a>
    </div>
    <div class="row">
        {% for i in movie_list %}
       <div class="ml-md-3 .ml-lg-0">
           <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.movie_img.url}}" alt=" " width="200px" height="300px">
                <div class="card-body" >
                <h5 class="card-title">{{i.movie_name}}</h5>
<!--                    <p class="card-text">{{i.movie_desc}}</p>-->
                <a href="{% url 'movieapp:movie_detail' i.id %}"class="btn btn-primary">Details</a>
                </div>
            </div>
       </div>
       {% endfor %}
    </div>
</div>


{% endblock %}